INSERT INTO AREAS(area) VALUES ('Strovolos');
INSERT INTO AREAS(area) VALUES ('Geri');
INSERT INTO AREAS(area) VALUES ('Latsia');
INSERT INTO AREAS(area) VALUES ('Lakatameia');
INSERT INTO AREAS(area) VALUES ('Dali (Ilioupoli)');
INSERT INTO AREAS(area) VALUES ('Agia Varvara Lefkosias');
INSERT INTO AREAS(area) VALUES ('Alampra');
INSERT INTO AREAS(area) VALUES ('Lythrodontas');
INSERT INTO AREAS(area) VALUES ('Lympia');
INSERT INTO AREAS(area) VALUES ('Pera Chorio');
INSERT INTO AREAS(area) VALUES ('Sia');
INSERT INTO AREAS(area) VALUES ('Klirou');
INSERT INTO AREAS(area) VALUES ('Agios Epifanios Oreinis');
INSERT INTO AREAS(area) VALUES ('Agios Ioannis Malountas');
INSERT INTO AREAS(area) VALUES ('Arediou');
INSERT INTO AREAS(area) VALUES ('Gourri');
INSERT INTO AREAS(area) VALUES ('Kalo Chorio Oreinis');
INSERT INTO AREAS(area) VALUES ('Agrokipia');
INSERT INTO AREAS(area) VALUES ('Episkopeio');
INSERT INTO AREAS(area) VALUES ('Ergates');
INSERT INTO AREAS(area) VALUES ('Kampia');
INSERT INTO AREAS(area) VALUES ('Kapedes');
INSERT INTO AREAS(area) VALUES ('Pera');
INSERT INTO AREAS(area) VALUES ('Kokkinotrimithia');
INSERT INTO AREAS(area) VALUES ('Mammari');
INSERT INTO AREAS(area) VALUES ('Palaiometocho');
INSERT INTO AREAS(area) VALUES ('Astromeritis');
INSERT INTO AREAS(area) VALUES ('Meniko');
INSERT INTO AREAS(area) VALUES ('Peristerona Lefkosias');
INSERT INTO AREAS(area) VALUES ('Palaichori Morfou');
INSERT INTO AREAS(area) VALUES ('Platanistasa');
INSERT INTO AREAS(area) VALUES ('Polystypos');
INSERT INTO AREAS(area) VALUES ('Agia Marina Xyliatou');
INSERT INTO AREAS(area) VALUES ('Nikitari');
INSERT INTO AREAS(area) VALUES ('Xyliatos');
INSERT INTO AREAS(area) VALUES ('Galata');
INSERT INTO AREAS(area) VALUES ('Evrychou');
INSERT INTO AREAS(area) VALUES ('Flasou');
INSERT INTO AREAS(area) VALUES ('Kampos');
INSERT INTO AREAS(area) VALUES ('Farmakas');
INSERT INTO AREAS(area) VALUES ('Aglantzia');
INSERT INTO AREAS(area) VALUES ('Palaichori Oreinis');
INSERT INTO AREAS(area) VALUES ('Egkomi');
INSERT INTO AREAS(area) VALUES ('Lefkosia (Pallouriotissa)');
INSERT INTO AREAS(area) VALUES ('Lefkosia');
INSERT INTO AREAS(area) VALUES ('Tseri');
INSERT INTO AREAS(area) VALUES ('Dali');
INSERT INTO AREAS(area) VALUES ('Mathiatis');
INSERT INTO AREAS(area) VALUES ('Malounta');
INSERT INTO AREAS(area) VALUES ('Psimolofou');
INSERT INTO AREAS(area) VALUES ('Agioi Trimithias');
INSERT INTO AREAS(area) VALUES ('Vyzakia');
INSERT INTO AREAS(area) VALUES ('Kaliana');
INSERT INTO AREAS(area) VALUES ('Kannavia');
INSERT INTO AREAS(area) VALUES ('Kato Deftera');
INSERT INTO AREAS(area) VALUES ('Kato Moni');
INSERT INTO AREAS(area) VALUES ('Askas');
INSERT INTO AREAS(area) VALUES ('Pano Deftera');
INSERT INTO AREAS(area) VALUES ('Dali (Kallithea)');
INSERT INTO AREAS(area) VALUES ('Nisou');
INSERT INTO AREAS(area) VALUES ('Orounta');
INSERT INTO AREAS(area) VALUES ('Lefkosia (Kaimakli)');
INSERT INTO AREAS(area) VALUES ('Lefkosia (Lykavittos)');
INSERT INTO AREAS(area) VALUES ('Agios Dometios');
INSERT INTO AREAS(area) VALUES ('Dali (Konstantia)');
INSERT INTO AREAS(area) VALUES ('Synoikismos Anthoupolis');
INSERT INTO AREAS(area) VALUES ('Anageia');
INSERT INTO AREAS(area) VALUES ('Akaki');
INSERT INTO AREAS(area) VALUES ('Kakopetria');
INSERT INTO AREAS(area) VALUES ('Potamia');
INSERT INTO AREAS(area) VALUES ('Politiko');
INSERT INTO AREAS(area) VALUES ('Analiontas');
INSERT INTO AREAS(area) VALUES ('Agia Eirini Lefkosias');
INSERT INTO AREAS(area) VALUES ('Kotsiatis');
INSERT INTO AREAS(area) VALUES ('Korakou');
INSERT INTO AREAS(area) VALUES ('Linou');
INSERT INTO AREAS(area) VALUES ('Pedoulas');
INSERT INTO AREAS(area) VALUES ('Kalopanagiotis');
INSERT INTO AREAS(area) VALUES ('Moutoullas');
INSERT INTO AREAS(area) VALUES ('Dali (Nea Lidra)');
INSERT INTO AREAS(area) VALUES ('Katydata');
INSERT INTO AREAS(area) VALUES ('Temvria');
INSERT INTO AREAS(area) VALUES ('Oikos');
INSERT INTO AREAS(area) VALUES ('Agioi Iliofotoi');
INSERT INTO AREAS(area) VALUES ('Apliki');
INSERT INTO AREAS(area) VALUES ('Mitsero');
INSERT INTO AREAS(area) VALUES ('Agios Georgios Kafkalou');
INSERT INTO AREAS(area) VALUES ('Agios Nikolaos Stegis');
INSERT INTO AREAS(area) VALUES ('Agios Sozomenos');
INSERT INTO AREAS(area) VALUES ('Spilia');
INSERT INTO AREAS(area) VALUES ('Deneia');
INSERT INTO AREAS(area) VALUES ('Kampi');
INSERT INTO AREAS(area) VALUES ('Kataliontas');
INSERT INTO AREAS(area) VALUES ('Lagoudera');
INSERT INTO AREAS(area) VALUES ('Potami');
INSERT INTO AREAS(area) VALUES ('Sinaoros');
INSERT INTO AREAS(area) VALUES ('Kato Pyrgos');
INSERT INTO AREAS(area) VALUES ('Tsakistra');
INSERT INTO AREAS(area) VALUES ('Alithinou');
INSERT INTO AREAS(area) VALUES ('Margi');
INSERT INTO AREAS(area) VALUES ('Asinou');
INSERT INTO AREAS(area) VALUES ('Dasikos Stathmos Kapouras');
INSERT INTO AREAS(area) VALUES ('Dasikos Stathmos Panagias');
INSERT INTO AREAS(area) VALUES ('Dasikos Stathmos Platanion');
INSERT INTO AREAS(area) VALUES ('Kato Koutrafas');
INSERT INTO AREAS(area) VALUES ('Fterikoudi');
INSERT INTO AREAS(area) VALUES ('Fikardou');
INSERT INTO AREAS(area) VALUES ('Filani');
INSERT INTO AREAS(area) VALUES ('Alona');
INSERT INTO AREAS(area) VALUES ('Livadia Lefkosias');
INSERT INTO AREAS(area) VALUES ('Gerakies');
INSERT INTO AREAS(area) VALUES ('Agios Theodoros Soleas');
INSERT INTO AREAS(area) VALUES ('Kourdali');
INSERT INTO AREAS(area) VALUES ('Lazanias');
INSERT INTO AREAS(area) VALUES ('Mansoura');
INSERT INTO AREAS(area) VALUES ('Moni Agiou Irakleidiou');
INSERT INTO AREAS(area) VALUES ('Moni Agiou Panteleimonos Achera');
INSERT INTO AREAS(area) VALUES ('Moni Archangelou Michail');
INSERT INTO AREAS(area) VALUES ('Moni Kykkou');
INSERT INTO AREAS(area) VALUES ('Moni Machaira');
INSERT INTO AREAS(area) VALUES ('Moni Panagias Theotokou');
INSERT INTO AREAS(area) VALUES ('Moni Profitou Iliou');
INSERT INTO AREAS(area) VALUES ('Mosfileri');
INSERT INTO AREAS(area) VALUES ('Mylikouri');
INSERT INTO AREAS(area) VALUES ('Pigenia');
INSERT INTO AREAS(area) VALUES ('Pachyammos');
INSERT INTO AREAS(area) VALUES ('Pano Koutrafas');
INSERT INTO AREAS(area) VALUES ('Skouriotissa');
INSERT INTO AREAS(area) VALUES ('Saranti');
INSERT INTO AREAS(area) VALUES ('Pano Pyrgos');
INSERT INTO AREAS(area) VALUES ('Lemesos');
INSERT INTO AREAS(area) VALUES ('Mesa Geitonia');
INSERT INTO AREAS(area) VALUES ('Ypsonas');
INSERT INTO AREAS(area) VALUES ('Kellaki');
INSERT INTO AREAS(area) VALUES ('Asgata');
INSERT INTO AREAS(area) VALUES ('Vasa Kellakiou');
INSERT INTO AREAS(area) VALUES ('Prastio Kellakiou');
INSERT INTO AREAS(area) VALUES ('Parekklisia');
INSERT INTO AREAS(area) VALUES ('Akrounta');
INSERT INTO AREAS(area) VALUES ('Pyrgos');
INSERT INTO AREAS(area) VALUES ('Paramytha');
INSERT INTO AREAS(area) VALUES ('Apesia');
INSERT INTO AREAS(area) VALUES ('Gerasa');
INSERT INTO AREAS(area) VALUES ('Korfi');
INSERT INTO AREAS(area) VALUES ('Mathikoloni');
INSERT INTO AREAS(area) VALUES ('Palodeia');
INSERT INTO AREAS(area) VALUES ('Spitali');
INSERT INTO AREAS(area) VALUES ('Kalo Chorio Lemesou');
INSERT INTO AREAS(area) VALUES ('Pissouri');
INSERT INTO AREAS(area) VALUES ('Episkopi Lemesou');
INSERT INTO AREAS(area) VALUES ('Erimi');
INSERT INTO AREAS(area) VALUES ('Kolossi');
INSERT INTO AREAS(area) VALUES ('Trachoni Lemesou');
INSERT INTO AREAS(area) VALUES ('Pachna');
INSERT INTO AREAS(area) VALUES ('Agios Amvrosios Lemesou');
INSERT INTO AREAS(area) VALUES ('Agios Therapon');
INSERT INTO AREAS(area) VALUES ('Pano Kivides');
INSERT INTO AREAS(area) VALUES ('Souni');
INSERT INTO AREAS(area) VALUES ('Silikou');
INSERT INTO AREAS(area) VALUES ('Moniatis');
INSERT INTO AREAS(area) VALUES ('Omodos');
INSERT INTO AREAS(area) VALUES ('Vasa Koilaniou');
INSERT INTO AREAS(area) VALUES ('Koilani');
INSERT INTO AREAS(area) VALUES ('Pera Pedi');
INSERT INTO AREAS(area) VALUES ('Kato Platres');
INSERT INTO AREAS(area) VALUES ('Agros');
INSERT INTO AREAS(area) VALUES ('Kyperounta');
INSERT INTO AREAS(area) VALUES ('Saittas');
INSERT INTO AREAS(area) VALUES ('Agios Athanasios');
INSERT INTO AREAS(area) VALUES ('Prastio Avdimou');
INSERT INTO AREAS(area) VALUES ('Troodos');
INSERT INTO AREAS(area) VALUES ('Agios Tychon');
INSERT INTO AREAS(area) VALUES ('Armenochori');
INSERT INTO AREAS(area) VALUES ('Moni');
INSERT INTO AREAS(area) VALUES ('Louvaras');
INSERT INTO AREAS(area) VALUES ('Akrotiri');
INSERT INTO AREAS(area) VALUES ('Zanakia');
INSERT INTO AREAS(area) VALUES ('Germasogeia');
INSERT INTO AREAS(area) VALUES ('Kantou');
INSERT INTO AREAS(area) VALUES ('Kolossi (Synoikismos)');
INSERT INTO AREAS(area) VALUES ('Kato Polemidia');
INSERT INTO AREAS(area) VALUES ('Agios Theodoros Lemesou');
INSERT INTO AREAS(area) VALUES ('Fasoula Lemesou');
INSERT INTO AREAS(area) VALUES ('Arsos Lemesou');
INSERT INTO AREAS(area) VALUES ('Pano Platres');
INSERT INTO AREAS(area) VALUES ('Vouni');
INSERT INTO AREAS(area) VALUES ('Pentakomo');
INSERT INTO AREAS(area) VALUES ('Mouttagiaka Touristiki Periochi');
INSERT INTO AREAS(area) VALUES ('Paramali');
INSERT INTO AREAS(area) VALUES ('Eptagoneia');
INSERT INTO AREAS(area) VALUES ('Foini');
INSERT INTO AREAS(area) VALUES ('Agios Thomas');
INSERT INTO AREAS(area) VALUES ('Pano Polemidia');
INSERT INTO AREAS(area) VALUES ('Mouttagiaka');
INSERT INTO AREAS(area) VALUES ('Monte Korfi');
INSERT INTO AREAS(area) VALUES ('Trimiklini');
INSERT INTO AREAS(area) VALUES ('Kouka');
INSERT INTO AREAS(area) VALUES ('Limnatis');
INSERT INTO AREAS(area) VALUES ('Zoopigi');
INSERT INTO AREAS(area) VALUES ('Asomatos Lemesou');
INSERT INTO AREAS(area) VALUES ('Lofou');
INSERT INTO AREAS(area) VALUES ('Monagri');
INSERT INTO AREAS(area) VALUES ('Doros');
INSERT INTO AREAS(area) VALUES ('Dora');
INSERT INTO AREAS(area) VALUES ('Monagroulli');
INSERT INTO AREAS(area) VALUES ('Mandria Lemesou');
INSERT INTO AREAS(area) VALUES ('Foinikaria');
INSERT INTO AREAS(area) VALUES ('Parekklisia Touristiki Periochi');
INSERT INTO AREAS(area) VALUES ('Agios Mamas');
INSERT INTO AREAS(area) VALUES ('Avdimou');
INSERT INTO AREAS(area) VALUES ('Apsiou');
INSERT INTO AREAS(area) VALUES ('Akapnou');
INSERT INTO AREAS(area) VALUES ('Dierona');
INSERT INTO AREAS(area) VALUES ('Sotira Lemesou');
INSERT INTO AREAS(area) VALUES ('Alassa');
INSERT INTO AREAS(area) VALUES ('Pelendri');
INSERT INTO AREAS(area) VALUES ('Agios Ioannis Lemesou');
INSERT INTO AREAS(area) VALUES ('Agios Tychon Touristiki Periochi');
INSERT INTO AREAS(area) VALUES ('Anogyra');
INSERT INTO AREAS(area) VALUES ('Agridia');
INSERT INTO AREAS(area) VALUES ('Agios Georgios Lemesou');
INSERT INTO AREAS(area) VALUES ('Alektora');
INSERT INTO AREAS(area) VALUES ('Arakapas');
INSERT INTO AREAS(area) VALUES ('Pyrgos Touristiki Periochi');
INSERT INTO AREAS(area) VALUES ('Kato Amiantos');
INSERT INTO AREAS(area) VALUES ('Agios Pavlos');
INSERT INTO AREAS(area) VALUES ('Laneia');
INSERT INTO AREAS(area) VALUES ('Sanida');
INSERT INTO AREAS(area) VALUES ('Agios Konstantinos');
INSERT INTO AREAS(area) VALUES ('Agios Dimitrios');
INSERT INTO AREAS(area) VALUES ('Chandria');
INSERT INTO AREAS(area) VALUES ('Potamitissa');
INSERT INTO AREAS(area) VALUES ('Fasouri');
INSERT INTO AREAS(area) VALUES ('Malia');
INSERT INTO AREAS(area) VALUES ('Tserkezoi');
INSERT INTO AREAS(area) VALUES ('Kaminaria');
INSERT INTO AREAS(area) VALUES ('Kapileio');
INSERT INTO AREAS(area) VALUES ('Kissousa');
INSERT INTO AREAS(area) VALUES ('Klonari');
INSERT INTO AREAS(area) VALUES ('Kato Mylos');
INSERT INTO AREAS(area) VALUES ('Lemithou');
INSERT INTO AREAS(area) VALUES ('Mesa Potamos');
INSERT INTO AREAS(area) VALUES ('Dymes');
INSERT INTO AREAS(area) VALUES ('Moni Agiou Georgiou Alamanou');
INSERT INTO AREAS(area) VALUES ('Moni Agiou Nikolaou Gaton');
INSERT INTO AREAS(area) VALUES ('Moni Evangelistrias');
INSERT INTO AREAS(area) VALUES ('Moni Panagias Trikoukkiotissis');
INSERT INTO AREAS(area) VALUES ('Moni Trooditissis');
INSERT INTO AREAS(area) VALUES ('Moni Zoodochou Pigis');
INSERT INTO AREAS(area) VALUES ('Palaiomylos');
INSERT INTO AREAS(area) VALUES ('Pano Amiantos');
INSERT INTO AREAS(area) VALUES ('Platanisteia');
INSERT INTO AREAS(area) VALUES ('Potamiou');
INSERT INTO AREAS(area) VALUES ('Prodromos');
INSERT INTO AREAS(area) VALUES ('Profitis Ilias');
INSERT INTO AREAS(area) VALUES ('Gerovasa');
INSERT INTO AREAS(area) VALUES ('Stathmos Filagron');
INSERT INTO AREAS(area) VALUES ('Sykopetra');
INSERT INTO AREAS(area) VALUES ('Treis Elies');
INSERT INTO AREAS(area) VALUES ('Vikla');
INSERT INTO AREAS(area) VALUES ('Liopetri');
INSERT INTO AREAS(area) VALUES ('Frenaros');
INSERT INTO AREAS(area) VALUES ('Deryneia');
INSERT INTO AREAS(area) VALUES ('Sotira Ammochostou');
INSERT INTO AREAS(area) VALUES ('Avgorou');
INSERT INTO AREAS(area) VALUES ('Dasaki Achnas');
INSERT INTO AREAS(area) VALUES ('Paralimni');
INSERT INTO AREAS(area) VALUES ('Agia Napa');
INSERT INTO AREAS(area) VALUES ('Acheritou');
INSERT INTO AREAS(area) VALUES ('Agia Thekla');
INSERT INTO AREAS(area) VALUES ('Agios Nikolaos Ammochostou');
INSERT INTO AREAS(area) VALUES ('Strovili');
INSERT INTO AREAS(area) VALUES ('Moni Agiou Kendeou');
INSERT INTO AREAS(area) VALUES ('Voroklini');
INSERT INTO AREAS(area) VALUES ('Livadia Larnakas');
INSERT INTO AREAS(area) VALUES ('Pyla');
INSERT INTO AREAS(area) VALUES ('Avdellero');
INSERT INTO AREAS(area) VALUES ('Troulloi');
INSERT INTO AREAS(area) VALUES ('Xylotymvou');
INSERT INTO AREAS(area) VALUES ('Xylofagou');
INSERT INTO AREAS(area) VALUES ('Ormideia');
INSERT INTO AREAS(area) VALUES ('Kiti');
INSERT INTO AREAS(area) VALUES ('Perivolia Larnakas');
INSERT INTO AREAS(area) VALUES ('Alethriko');
INSERT INTO AREAS(area) VALUES ('Anafotida');
INSERT INTO AREAS(area) VALUES ('Mazotos');
INSERT INTO AREAS(area) VALUES ('Athienou');
INSERT INTO AREAS(area) VALUES ('Kornos');
INSERT INTO AREAS(area) VALUES ('Mosfiloti');
INSERT INTO AREAS(area) VALUES ('Psevdas');
INSERT INTO AREAS(area) VALUES ('Pano Lefkara');
INSERT INTO AREAS(area) VALUES ('Agios Theodoros Larnakas');
INSERT INTO AREAS(area) VALUES ('Kalavasos');
INSERT INTO AREAS(area) VALUES ('Larnaka');
INSERT INTO AREAS(area) VALUES ('Aradippou');
INSERT INTO AREAS(area) VALUES ('Voroklini Tourist Area');
INSERT INTO AREAS(area) VALUES ('Dromolaxia');
INSERT INTO AREAS(area) VALUES ('Kellia');
INSERT INTO AREAS(area) VALUES ('Anglisides');
INSERT INTO AREAS(area) VALUES ('Meneou');
INSERT INTO AREAS(area) VALUES ('Pyla Touristiki Periochi');
INSERT INTO AREAS(area) VALUES ('Alaminos');
INSERT INTO AREAS(area) VALUES ('Tersefanou');
INSERT INTO AREAS(area) VALUES ('Choirokoitia');
INSERT INTO AREAS(area) VALUES ('Kalo Chorio Larnakas');
INSERT INTO AREAS(area) VALUES ('Kofinou');
INSERT INTO AREAS(area) VALUES ('Maroni');
INSERT INTO AREAS(area) VALUES ('Zygi');
INSERT INTO AREAS(area) VALUES ('Agia Anna');
INSERT INTO AREAS(area) VALUES ('Agioi Vavatsinias');
INSERT INTO AREAS(area) VALUES ('Pyrga Larnakas');
INSERT INTO AREAS(area) VALUES ('Kato Lefkara');
INSERT INTO AREAS(area) VALUES ('Psematismenos');
INSERT INTO AREAS(area) VALUES ('Skarinou');
INSERT INTO AREAS(area) VALUES ('Tochni');
INSERT INTO AREAS(area) VALUES ('Kivisili');
INSERT INTO AREAS(area) VALUES ('Vavatsinia');
INSERT INTO AREAS(area) VALUES ('Dekeleia');
INSERT INTO AREAS(area) VALUES ('Klavdia');
INSERT INTO AREAS(area) VALUES ('Delikipos');
INSERT INTO AREAS(area) VALUES ('Softades');
INSERT INTO AREAS(area) VALUES ('Kato Drys');
INSERT INTO AREAS(area) VALUES ('Lageia');
INSERT INTO AREAS(area) VALUES ('Mari');
INSERT INTO AREAS(area) VALUES ('Melini');
INSERT INTO AREAS(area) VALUES ('Menogeia');
INSERT INTO AREAS(area) VALUES ('Moni Agias Theklis');
INSERT INTO AREAS(area) VALUES ('Moni Agias Varvaras');
INSERT INTO AREAS(area) VALUES ('Moni Agiou Mina');
INSERT INTO AREAS(area) VALUES ('Moni Metamorfoseos tou Sotiros');
INSERT INTO AREAS(area) VALUES ('Moni Panagias Galaktotrofousis');
INSERT INTO AREAS(area) VALUES ('Moni Stavrovouniou');
INSERT INTO AREAS(area) VALUES ('Odou');
INSERT INTO AREAS(area) VALUES ('Ora');
INSERT INTO AREAS(area) VALUES ('Prosfygikos Synoikismos EAC');
INSERT INTO AREAS(area) VALUES ('Prosfygikos Synoikismos Vattaina');
INSERT INTO AREAS(area) VALUES ('Kosi');
INSERT INTO AREAS(area) VALUES ('Vasiliko');
INSERT INTO AREAS(area) VALUES ('Vavla');
INSERT INTO AREAS(area) VALUES ('Pafos');
INSERT INTO AREAS(area) VALUES ('Chlorakas');
INSERT INTO AREAS(area) VALUES ('Empa');
INSERT INTO AREAS(area) VALUES ('Mesogi');
INSERT INTO AREAS(area) VALUES ('Anarita');
INSERT INTO AREAS(area) VALUES ('Episkopi Pafou');
INSERT INTO AREAS(area) VALUES ('Tsada');
INSERT INTO AREAS(area) VALUES ('Kallepeia');
INSERT INTO AREAS(area) VALUES ('Polemi');
INSERT INTO AREAS(area) VALUES ('Stroumpi');
INSERT INTO AREAS(area) VALUES ('Kissonerga');
INSERT INTO AREAS(area) VALUES ('Panagia');
INSERT INTO AREAS(area) VALUES ('Polis');
INSERT INTO AREAS(area) VALUES ('Argaka');
INSERT INTO AREAS(area) VALUES ('Mesa Chorio');
INSERT INTO AREAS(area) VALUES ('Salamiou');
INSERT INTO AREAS(area) VALUES ('Timi');
INSERT INTO AREAS(area) VALUES ('Makounta');
INSERT INTO AREAS(area) VALUES ('Agia Marina Chrysochous');
INSERT INTO AREAS(area) VALUES ('Pegeia');
INSERT INTO AREAS(area) VALUES ('Polis (Prodromi)');
INSERT INTO AREAS(area) VALUES ('Steni');
INSERT INTO AREAS(area) VALUES ('Kouklia Pafou');
INSERT INTO AREAS(area) VALUES ('Geroskipou');
INSERT INTO AREAS(area) VALUES ('Tremithousa');
INSERT INTO AREAS(area) VALUES ('Kelokedara');
INSERT INTO AREAS(area) VALUES ('Geroskipou (Koloni)');
INSERT INTO AREAS(area) VALUES ('Konia');
INSERT INTO AREAS(area) VALUES ('Tala');
INSERT INTO AREAS(area) VALUES ('Nikokleia');
INSERT INTO AREAS(area) VALUES ('Lempa');
INSERT INTO AREAS(area) VALUES ('Marathounta');
INSERT INTO AREAS(area) VALUES ('Armou');
INSERT INTO AREAS(area) VALUES ('Drouseia');
INSERT INTO AREAS(area) VALUES ('Neo Chorio Pafou');
INSERT INTO AREAS(area) VALUES ('Ineia');
INSERT INTO AREAS(area) VALUES ('Statos - Agios Fotios');
INSERT INTO AREAS(area) VALUES ('Agia Marina Kelokedaron');
INSERT INTO AREAS(area) VALUES ('Kritou Tera');
INSERT INTO AREAS(area) VALUES ('Pelathousa');
INSERT INTO AREAS(area) VALUES ('Mandria Pafou');
INSERT INTO AREAS(area) VALUES ('Choletria');
INSERT INTO AREAS(area) VALUES ('Pegeia (Agios Georgios)');
INSERT INTO AREAS(area) VALUES ('Kathikas');
INSERT INTO AREAS(area) VALUES ('Giolou');
INSERT INTO AREAS(area) VALUES ('Theletra');
INSERT INTO AREAS(area) VALUES ('Letymvou');
INSERT INTO AREAS(area) VALUES ('Pegeia (Kolpos Korallion)');
INSERT INTO AREAS(area) VALUES ('Arminou');
INSERT INTO AREAS(area) VALUES ('Pano Akourdaleia');
INSERT INTO AREAS(area) VALUES ('Gialia');
INSERT INTO AREAS(area) VALUES ('Agia Marinouda');
INSERT INTO AREAS(area) VALUES ('Miliou');
INSERT INTO AREAS(area) VALUES ('Kedares');
INSERT INTO AREAS(area) VALUES ('Lemona');
INSERT INTO AREAS(area) VALUES ('Amargeti');
INSERT INTO AREAS(area) VALUES ('Kouklia Pafou (Cha Potami)');
INSERT INTO AREAS(area) VALUES ('Agios Dimitrianos');
INSERT INTO AREAS(area) VALUES ('Agios Georgios Pafou');
INSERT INTO AREAS(area) VALUES ('Agios Nikolaos Pafou');
INSERT INTO AREAS(area) VALUES ('Skoulli');
INSERT INTO AREAS(area) VALUES ('Goudi');
INSERT INTO AREAS(area) VALUES ('Peristerona Pafou');
INSERT INTO AREAS(area) VALUES ('Pomos');
INSERT INTO AREAS(area) VALUES ('Koili');
INSERT INTO AREAS(area) VALUES ('Nata');
INSERT INTO AREAS(area) VALUES ('Mamonia');
INSERT INTO AREAS(area) VALUES ('Agios Ioannis Pafou');
INSERT INTO AREAS(area) VALUES ('Kato Akourdaleia');
INSERT INTO AREAS(area) VALUES ('Lysos');
INSERT INTO AREAS(area) VALUES ('Polis (Latsi)');
INSERT INTO AREAS(area) VALUES ('Akoursos');
INSERT INTO AREAS(area) VALUES ('Fyti');
INSERT INTO AREAS(area) VALUES ('Anadiou');
INSERT INTO AREAS(area) VALUES ('Chrysochou');
INSERT INTO AREAS(area) VALUES ('Fasoula Pafou');
INSERT INTO AREAS(area) VALUES ('Choli');
INSERT INTO AREAS(area) VALUES ('Acheleia');
INSERT INTO AREAS(area) VALUES ('Asprogia');
INSERT INTO AREAS(area) VALUES ('Axylou');
INSERT INTO AREAS(area) VALUES ('Nea Dimmata');
INSERT INTO AREAS(area) VALUES ('Androlikou');
INSERT INTO AREAS(area) VALUES ('Choulou');
INSERT INTO AREAS(area) VALUES ('Dasikos Stathmos Agias');
INSERT INTO AREAS(area) VALUES ('Dasikos Stathmos Stavrou tis Psokas');
INSERT INTO AREAS(area) VALUES ('Drymou');
INSERT INTO AREAS(area) VALUES ('Eledio');
INSERT INTO AREAS(area) VALUES ('Meladeia');
INSERT INTO AREAS(area) VALUES ('Kato Arodes');
INSERT INTO AREAS(area) VALUES ('Evretou');
INSERT INTO AREAS(area) VALUES ('Fylousa Chrysochous');
INSERT INTO AREAS(area) VALUES ('Fylousa Kelokedaron');
INSERT INTO AREAS(area) VALUES ('Galataria');
INSERT INTO AREAS(area) VALUES ('Kannaviou');
INSERT INTO AREAS(area) VALUES ('Praitori');
INSERT INTO AREAS(area) VALUES ('Kato Archimandrita');
INSERT INTO AREAS(area) VALUES ('Kidasi');
INSERT INTO AREAS(area) VALUES ('Koilineia');
INSERT INTO AREAS(area) VALUES ('Kouklia Pafou (Lofoi Afroditis)');
INSERT INTO AREAS(area) VALUES ('Kourdaka');
INSERT INTO AREAS(area) VALUES ('Kritou Marottou');
INSERT INTO AREAS(area) VALUES ('Kynousa');
INSERT INTO AREAS(area) VALUES ('Lapithiou');
INSERT INTO AREAS(area) VALUES ('Lasa');
INSERT INTO AREAS(area) VALUES ('Limni');
INSERT INTO AREAS(area) VALUES ('Mamountali');
INSERT INTO AREAS(area) VALUES ('Melamiou');
INSERT INTO AREAS(area) VALUES ('Mesana');
INSERT INTO AREAS(area) VALUES ('Milia Pafou');
INSERT INTO AREAS(area) VALUES ('Moni Agion Anargyron');
INSERT INTO AREAS(area) VALUES ('Moni Agiou Neofytou');
INSERT INTO AREAS(area) VALUES ('Moni Chrysorrogiatissis');
INSERT INTO AREAS(area) VALUES ('Mousere');
INSERT INTO AREAS(area) VALUES ('Pano Archimandrita');
INSERT INTO AREAS(area) VALUES ('Pano Arodes');
INSERT INTO AREAS(area) VALUES ('Pentalia');
INSERT INTO AREAS(area) VALUES ('Prastio Pafou');
INSERT INTO AREAS(area) VALUES ('Psathi');
INSERT INTO AREAS(area) VALUES ('Simou');
INSERT INTO AREAS(area) VALUES ('Stavrokonnou');
INSERT INTO AREAS(area) VALUES ('Tera');
INSERT INTO AREAS(area) VALUES ('Thrinia');
INSERT INTO AREAS(area) VALUES ('Trachypedoula');
INSERT INTO AREAS(area) VALUES ('Trimithousa');
INSERT INTO AREAS(area) VALUES ('Agia Varvara Pafou');