INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('1','Ainu');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('2','Albanian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('3','Argentine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('4','Andhra');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('5','American');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('6','Anglo-Indian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('7','Arab');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('8','Armenian ');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('9','Assyrian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('10','Awadhi');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('11','Azerbaijani');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('12','Balochi');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('13','Bashkir');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('14','Belarusian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('15','Bangladeshi');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('16','Bengali');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('17','Berber');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('18','Brazilian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('19','British');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('20','Buddhist');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('21','Bulgarian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('22','Cajun');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('23','Cantonese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('24','Caribbean');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('25','Chechen');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('26','Chinese cuisine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('27','Chinese Islamic');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('28','Circassian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('29','Crimean Tatar');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('30','Cypriot');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('31','Czech');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('32','Danish');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('33','Egyptian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('34','English');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('35','Ethiopian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('36','Eritrean');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('37','Estonian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('38','French');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('39','Filipino');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('40','Georgian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('41','German');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('42','Goan');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('43','Goan Catholic');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('44','Greek');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('45','Gujarati');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('46','Hyderabad');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('47','Indian cuisine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('48','Indian Chinese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('49','Indian Singaporean cuisine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('50','Indonesian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('51','Inuit');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('52','Irish');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('53','Italian-American');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('54','Italian cuisine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('55','Jamaican');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('56','Japanese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('57','Jewish');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('58','Karnataka');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('59','Kazakh');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('60','Keralite');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('61','Korean');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('62','Kurdish');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('63','Laotian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('64','Lebanese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('65','Latvian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('66','Lithuanian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('67','Louisiana Creole');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('68','Maharashtrian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('69','Mangalorean');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('70','Malay');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('71','Malaysian Chinese cuisine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('72','Malaysian Indian cuisine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('73','Mediterranean cuisine');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('74','Mennonite');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('75','Mexican');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('76','Mordovian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('77','Mughal');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('78','Native American');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('79','Nepalese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('80','New Mexican');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('81','Odia');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('82','Parsi');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('83','Pashtun');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('84','Polish');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('85','Pennsylvania Dutch');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('86','Pakistani');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('87','Peranakan');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('88','Persian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('89','Peruvian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('90','Portuguese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('91','Punjabi');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('92','Québécois');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('93','Rajasthani');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('94','Romanian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('95','Russian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('96','Sami');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('97','Serbian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('98','Sindhi');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('99','Slovak');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('100','Slovenian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('101','Somali');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('102','South Indian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('103','Soviet');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('104','Spanish');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('105','Sri Lankan');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('106','Taiwanese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('107','Tatar');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('108','Texan');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('109','Thai');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('110','Turkish');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('111','Tamil');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('112','Udupi');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('113','Ukrainian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('114','Vietnamese');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('115','Yamal');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('116','Zambian');
INSERT INTO `reservi9_epl343`.`CUISINES` (id,cuisine_type) VALUES ('117','Zanzibari');